<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Nombre: Pablo Lin
Curso: 1DAW 
Fecha: 1/04/2025 
Ejercicio: XML_DTD4
-->
<!DOCTYPE vuelos [
<!ELEMENT vuelos (vuelo*)>
<!ELEMENT vuelo ((origen, destino) | (destino, origen))>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
]>

<vuelos>
    <vuelo>
        <origen>Valencia (VLC)</origen>
        <destino>Londres Heathrow (LHR)</destino>
    </vuelo>
    <vuelo>
        <destino>Berlín Schönefeld (SFX)</destino>
        <origen>París Charles de Gaulle (CDG)</origen>
    </vuelo>
</vuelos>